name: "<card-name>"
category: "optimization"
input_shape: ["n"]
output_shape: []
domain:
  description: "Define constraints and avoid invalid boundary points."
api:
  value: implemented
  grad: implemented
  hess: not_implemented
  hvp: implemented
  domain_sample: implemented
  check: implemented
dependencies:
  lemmas: []
references: []
tags:
  - derivative-card
  - analytic-derivative
